---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r}
data <- read.table(file="e:\\test2\\activity.csv",head=TRUE,sep=",")
```


## What is mean total number of steps taken per day?
```{r}
aggdata_steps_by_date <-aggregate(data$steps, by=list(data$date), FUN=sum, na.rm=TRUE)
hist(aggdata_steps_by_date$x,main= " Frequency of Total number of steps taken each day", xlab="Total number of steps taken each day")

print(mean(aggdata_steps_by_date$x))
print(median(aggdata_steps_by_date$x))
```

## What is the average daily activity pattern?
```{r}
aggdata_steps_by_interval <-aggregate(data$steps, by=list(data$interval), FUN=mean, na.rm=TRUE)
plot(aggdata_steps_by_interval$Group.1,aggdata_steps_by_interval$x, type='l',xlab="Interval", ylab="Average across all days")
max_five_minute = which.max(aggdata_steps_by_interval$x)
p=aggdata_steps_by_interval[max_five_minute,]
print("max 5-minute interval, on average across all the days having max steps")
print(p$Group.1)
```


## Imputing missing values
```{r}
na_data <-subset(data,is.na(data))
print("total number of missing values in the dataset")
print(length(na_data$steps))
data[is.na(data),1] <- aggdata_steps_by_date[data[is.na(data),2],2]
aggdata_steps_by_date <-aggregate(data$steps, by=list(data$date), FUN=sum, na.rm=TRUE)
hist(aggdata_steps_by_date$x,main= " Frequency of Total number of steps taken each day", xlab="Total number of steps taken each day")

print(mean(aggdata_steps_by_date$x))
print(median(aggdata_steps_by_date$x))
```

## Are there differences in activity patterns between weekdays and weekends?
```{r}
data[,"weekday"] <- NA
data$weekday <- weekdays(as.Date(data$date))
```